# Generated by Django 3.1 on 2022-01-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220110_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(upload_to='images'),
        ),
    ]
