# Generated by Django 3.1 on 2022-01-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220117_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, default='../static/images/avatars/user-01.jpeg', upload_to='images'),
        ),
    ]
